version: '3'

services:
  database:
    image: 'postgres:latest'

    ports:
      - 5431:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: default_database